site_name: Uber Go Style Guide
site_author: Uber Technologies, Inc
site_description: Documentation of patterns and conventions used in Go code at Uber.

theme:
  name: "material"
  include_sidebar: false
  include_search_page: false
  search_index_only: false
  include_homepage_in_sidebar: false
  prev_next_buttons_location: "bottom"
google_analytics:
  - "UA-89201129-1"
  - "https://zchee.github.io/uber-go-guide/"
repo_name: zchee/uber-go-guide
site_url: https://zchee.github.io/uber-go-guide/
repo_url: https://github.com/zchee/uber-go-guide/
docs_dir: "./docs"
site_dir: "./site"

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search

nav:
  - "Style Guide": index.md
  - "README": home.md
  - "CHANGELOG": changelog.md
  - "LICENSE": license.md
  - "CODE OF CONDUCT": code_of_conduct.md
