name: gh pages

on:
  push:
    branches:
      - mkdocs

jobs:
  gh-pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup mkdocs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

      - name: Build and deploy to gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
        uses: docker://squidfunk/mkdocs-material:latest
        with:
          entrypoint: sh
          args: -c "mkdocs build --clean --verbose && mkdocs gh-deploy --verbose --force"
